---
title: "R Markdown 4"
author: "Victor C. Ezeh"
date: "2023-05-01"
output: html_document
---

```{r}
#We use ggplot package to make visualizations in R
#We can put our plot in a variable name or we just basically go ahead with our plotting
#Plot the best time of the month
#To plot within R, we need to specify the subject matter i.e best time of the month, then afterwards, specify the x and y axis. And to do that, we need to use a parameter called AES. After using the AES parameter, we need to specify the x axis first the followed by the y axis
#The next thing is to tell R the kind of plot you want
#The types of Geom - geom bar, geom boxplot, geom column, geom contour line, geom curve, geom smooth
#We use the re-order function to re-order the values to take it from the lowest to the highest.

#Represent the best time of the month on a bar chart

ggplot(Best_Time_Month, aes(x = reorder(MM, prop_of_delay), y = prop_of_delay, fill = MM)) + geom_bar(stat = "identity")
```
```{r}
#Represent the best time of the week on a point graph

ggplot(Best_Time_Week, aes(x = Week_Day, y = prop_of_delay, shape = Week_Day)) + geom_point()
```
```{r}
#Represent the best time of the week on a bar chart

ggplot(Best_Time_Week, aes(x = reorder(Week_Day, prop_of_delay), y = prop_of_delay, fill = Week_Day)) + geom_bar(stat = "identity")
```

```{r}
#Y Limit in R is used to further inestigate a section of the dataset

ggplot(Best_Time_Month, aes(x = MM, y = prop_of_delay, fill = MM)) + geom_point() + ylim(0.06, 0.065)
```

```{r}
#Task
#Represent the best time of the month on a point graph

ggplot(Best_Time_Month, aes(x = MM, y = prop_of_delay)) + geom_point()
```

```{r}
#Task 2
#Represent the best time of the day on a column chart

ggplot(Best_Time_Day, aes(x = reorder(Time_Day, prop_of_delay), y = prop_of_delay, fill = Time_Day)) + geom_col(stat = "identity")
```

